kafka:
  configuration:
    bootstrapServers: localhost:9092
spring:
  application:
    name: RecomendationService
  profiles:
    active: test
recomendations:
  max: 
    per:
      user: 3
server:
  port: 8001